/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'davicon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'davicon-point-up' : '&#xe000;',
			'davicon-point-right' : '&#xe001;',
			'davicon-point-left' : '&#xe002;',
			'davicon-point-down' : '&#xe003;',
			'davicon-disapprove' : '&#xe004;',
			'davicon-approve' : '&#xe005;',
			'davicon-action-tap' : '&#xe006;',
			'davicon-action-hold' : '&#xe007;',
			'davicon-handheld' : '&#xe008;',
			'davicon-desktop' : '&#xe009;',
			'davicon-controller' : '&#xe00a;',
			'davicon-tablet-portrait' : '&#xe00b;',
			'davicon-tablet-landscape' : '&#xe00c;',
			'davicon-mobile-portrait' : '&#xe00d;',
			'davicon-mobile-landscape' : '&#xe00e;',
			'davicon-list-bulleted' : '&#xe00f;',
			'davicon-list' : '&#xe010;',
			'davicon-grid' : '&#xe011;',
			'davicon-align-right' : '&#xe012;',
			'davicon-align-left' : '&#xe013;',
			'davicon-align-centre' : '&#xe014;',
			'davicon-up-outer' : '&#xe015;',
			'davicon-up' : '&#xe016;',
			'davicon-top-right-outer' : '&#xe017;',
			'davicon-top-right' : '&#xe018;',
			'davicon-top-left-outer' : '&#xe019;',
			'davicon-top-left' : '&#xe01a;',
			'davicon-right-outer' : '&#xe01b;',
			'davicon-right' : '&#xe01c;',
			'davicon-left-outer' : '&#xe01d;',
			'davicon-left' : '&#xe01e;',
			'davicon-down-outer' : '&#xe01f;',
			'davicon-down' : '&#xe020;',
			'davicon-chevron-right' : '&#xe021;',
			'davicon-chevron-left' : '&#xe022;',
			'davicon-bottom-right-outer' : '&#xe023;',
			'davicon-bottom-right' : '&#xe024;',
			'davicon-bottom-left-outer' : '&#xe025;',
			'davicon-bottom-left' : '&#xe026;',
			'davicon-both-directions' : '&#xe027;',
			'davicon-volume-3' : '&#xe028;',
			'davicon-volume-2' : '&#xe029;',
			'davicon-volume-1' : '&#xe02a;',
			'davicon-volume' : '&#xe02b;',
			'davicon-users' : '&#xe02c;',
			'davicon-user' : '&#xe02d;',
			'davicon-usb' : '&#xe02e;',
			'davicon-unlock' : '&#xe02f;',
			'davicon-unlink' : '&#xe030;',
			'davicon-underscore' : '&#xe031;',
			'davicon-twitter' : '&#xe032;',
			'davicon-triangle-outer' : '&#xe033;',
			'davicon-triangle' : '&#xe034;',
			'davicon-times' : '&#xe035;',
			'davicon-tick' : '&#xe036;',
			'davicon-thumbtack' : '&#xe037;',
			'davicon-tag' : '&#xe038;',
			'davicon-switch-on' : '&#xe039;',
			'davicon-switch-off' : '&#xe03a;',
			'davicon-sun' : '&#xe03b;',
			'davicon-stop' : '&#xe03c;',
			'davicon-star-outer' : '&#xe03d;',
			'davicon-star' : '&#xe03e;',
			'davicon-staddle' : '&#xe03f;',
			'davicon-square-outer' : '&#xe040;',
			'davicon-square' : '&#xe041;',
			'davicon-speech' : '&#xe042;',
			'davicon-spark-2' : '&#xe043;',
			'davicon-spark' : '&#xe044;',
			'davicon-snooze' : '&#xe045;',
			'davicon-shuffle' : '&#xe046;',
			'davicon-shrink-screen' : '&#xe047;',
			'davicon-settings' : '&#xe048;',
			'davicon-service-cloud-upload' : '&#xe049;',
			'davicon-service-cloud-download' : '&#xe04a;',
			'davicon-service-cloud' : '&#xe04b;',
			'davicon-search' : '&#xe04c;',
			'davicon-save' : '&#xe04d;',
			'davicon-same-window' : '&#xe04e;',
			'davicon-rubbish-full' : '&#xe04f;',
			'davicon-rubbish' : '&#xe050;',
			'davicon-rewind' : '&#xe051;',
			'davicon-retweet' : '&#xe052;',
			'davicon-repeat' : '&#xe053;',
			'davicon-reduce' : '&#xe054;',
			'davicon-rating-half' : '&#xe055;',
			'davicon-rating-full' : '&#xe056;',
			'davicon-rating-empty' : '&#xe057;',
			'davicon-question' : '&#xe058;',
			'davicon-power' : '&#xe059;',
			'davicon-polaroid' : '&#xe05a;',
			'davicon-plus' : '&#xe05b;',
			'davicon-play' : '&#xe05c;',
			'davicon-pin' : '&#xe05d;',
			'davicon-pie-chart' : '&#xe05e;',
			'davicon-photos' : '&#xe05f;',
			'davicon-percent' : '&#xe060;',
			'davicon-pencil' : '&#xe061;',
			'davicon-pause' : '&#xe062;',
			'davicon-pages' : '&#xe063;',
			'davicon-page' : '&#xe064;',
			'davicon-new-window' : '&#xe065;',
			'davicon-new-page' : '&#xe066;',
			'davicon-mute' : '&#xe067;',
			'davicon-minus' : '&#xe068;',
			'davicon-mic' : '&#xe069;',
			'davicon-map-pin' : '&#xe06a;',
			'davicon-map' : '&#xe06b;',
			'davicon-male' : '&#xe06c;',
			'davicon-mail' : '&#xe06d;',
			'davicon-lock' : '&#xe06e;',
			'davicon-locate' : '&#xe06f;',
			'davicon-loading' : '&#xe070;',
			'davicon-load' : '&#xe071;',
			'davicon-link' : '&#xe072;',
			'davicon-lens' : '&#xe073;',
			'davicon-info' : '&#xe074;',
			'davicon-hyphen' : '&#xe075;',
			'davicon-hint-plus' : '&#xe076;',
			'davicon-hint-minus' : '&#xe077;',
			'davicon-hex-outer' : '&#xe078;',
			'davicon-hex' : '&#xe079;',
			'davicon-heart' : '&#xe07a;',
			'davicon-group' : '&#xe07b;',
			'davicon-globe' : '&#xe07c;',
			'davicon-full-screen' : '&#xe07d;',
			'davicon-forward' : '&#xe07e;',
			'davicon-folder-open' : '&#xe07f;',
			'davicon-folder' : '&#xe080;',
			'davicon-floppy' : '&#xe081;',
			'davicon-flag-alt' : '&#xe082;',
			'davicon-flag' : '&#xe083;',
			'davicon-fire' : '&#xe084;',
			'davicon-female' : '&#xe085;',
			'davicon-fast-rewind' : '&#xe086;',
			'davicon-fast-forward' : '&#xe087;',
			'davicon-facebook' : '&#xe088;',
			'davicon-exclaim' : '&#xe089;',
			'davicon-equals' : '&#xe08a;',
			'davicon-enlarge' : '&#xe08b;',
			'davicon-ellipses' : '&#xe08c;',
			'davicon-eject' : '&#xe08d;',
			'davicon-drop' : '&#xe08e;',
			'davicon-document' : '&#xe08f;',
			'davicon-divide' : '&#xe090;',
			'davicon-disc' : '&#xe091;',
			'davicon-cross' : '&#xe092;',
			'davicon-conversation' : '&#xe093;',
			'davicon-cloud' : '&#xe094;',
			'davicon-clipboard' : '&#xe095;',
			'davicon-circle-outer' : '&#xe096;',
			'davicon-circle' : '&#xe097;',
			'davicon-character' : '&#xe098;',
			'davicon-camera' : '&#xe099;',
			'davicon-calendar-blank' : '&#xe09a;',
			'davicon-calendar' : '&#xe09b;',
			'davicon-bullet' : '&#xe09c;',
			'davicon-bookmarked' : '&#xe09d;',
			'davicon-bookmark' : '&#xe09e;',
			'davicon-book' : '&#xe09f;',
			'davicon-blank' : '&#xe0a0;',
			'davicon-battery-low' : '&#xe0a1;',
			'davicon-battery-half' : '&#xe0a2;',
			'davicon-battery-full' : '&#xe0a3;',
			'davicon-battery-empty' : '&#xe0a4;',
			'davicon-bar-chart' : '&#xe0a5;',
			'davicon-asterisk' : '&#xe0a6;',
			'davicon-art' : '&#xe0a7;',
			'davicon-alarm' : '&#xe0a8;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};